/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Aug 31 21:04:01 GMT 2026
 */

package org.apache.storm.redis.bolt;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class RedisFilterBolt_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.storm.redis.bolt.RedisFilterBolt"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(RedisFilterBolt_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.storm.topology.OutputFieldsDeclarer",
      "org.apache.storm.redis.common.mapper.RedisMapper",
      "org.apache.storm.task.TopologyContext",
      "org.apache.storm.topology.base.BaseComponent",
      "org.apache.storm.shade.net.minidev.json.JSONAware",
      "org.apache.storm.redis.bolt.RedisFilterBolt$1",
      "org.apache.storm.task.GeneralTopologyContext",
      "org.apache.storm.tuple.Tuple",
      "org.apache.storm.task.WorkerTopologyContext",
      "org.apache.storm.task.OutputCollector",
      "org.apache.storm.redis.common.mapper.RedisDataTypeDescription",
      "org.apache.storm.redis.common.config.JedisPoolConfig",
      "org.apache.storm.task.IMetricsContext",
      "org.apache.storm.task.IErrorReporter",
      "org.apache.storm.redis.bolt.RedisFilterBolt",
      "org.apache.storm.topology.base.BaseRichBolt",
      "org.apache.storm.topology.base.BaseTickTupleAwareRichBolt",
      "org.apache.storm.task.IBolt",
      "org.apache.storm.topology.OutputFieldsGetter",
      "org.apache.storm.redis.common.mapper.RedisDataTypeDescription$RedisDataType",
      "org.apache.storm.tuple.Fields",
      "org.apache.storm.tuple.ITuple",
      "org.apache.storm.redis.common.config.JedisClusterConfig",
      "org.apache.storm.task.IOutputCollector",
      "org.apache.storm.redis.common.container.JedisCommandsContainer",
      "org.apache.storm.redis.bolt.AbstractRedisBolt",
      "org.apache.storm.redis.common.mapper.TupleMapper",
      "org.apache.storm.topology.IRichBolt",
      "org.apache.storm.redis.common.mapper.RedisFilterMapper",
      "org.apache.storm.topology.IComponent"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.apache.storm.redis.common.mapper.RedisDataTypeDescription", false, RedisFilterBolt_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.storm.redis.common.mapper.RedisFilterMapper", false, RedisFilterBolt_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(RedisFilterBolt_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.storm.topology.base.BaseComponent",
      "org.apache.storm.topology.base.BaseRichBolt",
      "org.apache.storm.topology.base.BaseTickTupleAwareRichBolt",
      "org.apache.storm.redis.bolt.AbstractRedisBolt",
      "org.apache.storm.redis.bolt.RedisFilterBolt",
      "org.apache.storm.redis.common.mapper.RedisDataTypeDescription$RedisDataType",
      "org.apache.storm.redis.bolt.RedisFilterBolt$1",
      "org.apache.storm.redis.common.config.JedisPoolConfig",
      "org.apache.storm.redis.common.config.JedisClusterConfig",
      "com.google.common.base.Preconditions",
      "redis.clients.jedis.GeoCoordinate",
      "org.apache.storm.thrift.transport.TTransport",
      "org.apache.storm.thrift.transport.TEndpointTransport",
      "org.apache.storm.thrift.transport.TByteBuffer",
      "org.apache.storm.thrift.TConfiguration$Builder",
      "org.apache.storm.thrift.TConfiguration",
      "org.apache.storm.thrift.protocol.TProtocol",
      "org.apache.storm.thrift.protocol.TStruct",
      "org.apache.storm.thrift.protocol.TField",
      "org.apache.storm.thrift.protocol.TCompactProtocol",
      "org.apache.storm.thrift.protocol.TTupleProtocol",
      "org.apache.storm.thrift.protocol.ShortStack",
      "org.apache.storm.thrift.protocol.TSet",
      "org.apache.storm.thrift.protocol.TList",
      "org.apache.storm.thrift.TException",
      "org.apache.storm.thrift.protocol.TProtocolException",
      "org.apache.storm.shade.io.netty.channel.unix.FileDescriptor",
      "org.apache.storm.shade.io.netty.channel.unix.Socket",
      "org.apache.storm.shade.io.netty.channel.epoll.LinuxSocket",
      "org.apache.storm.thrift.transport.TSimpleFileTransport",
      "org.apache.storm.thrift.transport.TNonblockingTransport",
      "org.apache.storm.thrift.transport.TNonblockingSocket",
      "org.apache.storm.thrift.transport.TSaslTransport",
      "org.apache.storm.thrift.transport.TSaslServerTransport",
      "org.apache.storm.thrift.TByteArrayOutputStream",
      "org.apache.storm.thrift.transport.TMemoryInputTransport",
      "org.apache.storm.thrift.transport.TTransportException",
      "org.apache.storm.thrift.transport.TMemoryBuffer",
      "org.apache.storm.thrift.transport.TMemoryTransport",
      "org.apache.storm.thrift.transport.TIOStreamTransport",
      "org.apache.storm.thrift.transport.TSocket",
      "org.apache.storm.shade.io.netty.util.DefaultAttributeMap",
      "org.apache.storm.shade.io.netty.util.internal.logging.InternalLoggerFactory",
      "org.apache.storm.shade.io.netty.util.internal.logging.Slf4JLoggerFactory",
      "org.apache.storm.shade.io.netty.util.internal.logging.Slf4JLoggerFactory$NopInstanceHolder",
      "org.apache.storm.shade.io.netty.util.internal.logging.AbstractInternalLogger",
      "org.apache.storm.shade.io.netty.util.internal.logging.LocationAwareSlf4JLogger",
      "org.apache.storm.shade.io.netty.util.internal.ObjectUtil",
      "org.apache.storm.shade.io.netty.channel.AbstractChannel",
      "org.apache.storm.shade.io.netty.channel.ChannelMetadata",
      "org.apache.storm.shade.io.netty.channel.kqueue.AbstractKQueueChannel",
      "org.apache.storm.shade.io.netty.util.internal.SystemPropertyUtil",
      "org.apache.storm.shade.io.netty.util.internal.StringUtil",
      "org.apache.storm.shade.io.netty.channel.kqueue.AbstractKQueueStreamChannel",
      "org.apache.storm.shade.io.netty.channel.kqueue.KQueueSocketChannel",
      "org.apache.storm.shade.io.netty.channel.kqueue.BsdSocket",
      "org.apache.storm.redis.common.mapper.RedisDataTypeDescription",
      "org.apache.storm.topology.OutputFieldsGetter",
      "org.apache.storm.shade.io.netty.channel.epoll.AbstractEpollChannel",
      "org.apache.storm.shade.io.netty.channel.epoll.AbstractEpollStreamChannel",
      "org.apache.storm.shade.io.netty.channel.epoll.EpollSocketChannel",
      "org.apache.storm.task.OutputCollector",
      "org.apache.storm.tuple.Fields",
      "org.apache.storm.utils.TupleUtils",
      "org.apache.storm.generated.SupervisorInfo$SupervisorInfoStandardSchemeFactory",
      "org.apache.storm.generated.SupervisorInfo$SupervisorInfoTupleSchemeFactory",
      "org.apache.storm.generated.SupervisorInfo$_Fields",
      "org.apache.storm.thrift.meta_data.FieldMetaData",
      "org.apache.storm.thrift.meta_data.FieldValueMetaData",
      "org.apache.storm.thrift.meta_data.ListMetaData",
      "org.apache.storm.thrift.meta_data.MapMetaData",
      "org.apache.storm.generated.SupervisorInfo",
      "org.apache.storm.thrift.EncodingUtils",
      "org.apache.storm.generated.Credentials$CredentialsStandardSchemeFactory",
      "org.apache.storm.generated.Credentials$CredentialsTupleSchemeFactory",
      "org.apache.storm.generated.Credentials$_Fields",
      "org.apache.storm.generated.Credentials",
      "org.apache.storm.executor.Executor",
      "org.apache.storm.thrift.transport.TFileTransport",
      "org.apache.storm.thrift.transport.TFileTransport$TailPolicy",
      "org.apache.storm.thrift.transport.TStandardFile",
      "org.apache.storm.tuple.TupleImpl",
      "org.apache.storm.tuple.MessageId",
      "org.apache.storm.daemon.Task",
      "org.apache.storm.thrift.transport.TSaslClientTransport",
      "org.apache.storm.thrift.transport.TSaslTransport$SaslParticipant",
      "org.apache.storm.messaging.local.Context",
      "redis.clients.jedis.Response",
      "org.apache.storm.cluster.ClusterStateContext",
      "org.apache.storm.cluster.ZKStateStorage",
      "org.apache.storm.shade.io.netty.channel.epoll.AbstractEpollServerChannel",
      "org.apache.storm.shade.io.netty.channel.epoll.EpollServerSocketChannel",
      "org.apache.storm.thrift.protocol.TMap",
      "org.apache.storm.thrift.transport.AutoExpandingBufferWriteTransport",
      "org.apache.storm.thrift.transport.TZlibTransport",
      "org.apache.storm.thrift.transport.TTransportInputStream",
      "org.apache.storm.thrift.transport.TTransportOutputStream",
      "org.apache.storm.shade.io.netty.channel.epoll.EpollDatagramChannel",
      "org.apache.storm.shade.io.netty.channel.kqueue.AbstractKQueueDatagramChannel",
      "org.apache.storm.shade.io.netty.channel.kqueue.KQueueDatagramChannel",
      "org.apache.storm.shade.io.netty.channel.socket.InternetProtocolFamily$1",
      "org.apache.storm.shade.io.netty.util.NetUtilInitializations",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent0$1",
      "org.apache.storm.shade.io.netty.util.internal.ReflectionUtil",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent0$2",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent0$3",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent0$4",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent0$5",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent0$6",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent0$7",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent0$9",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent0",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent$1",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent$2",
      "org.apache.storm.shade.io.netty.util.internal.CleanerJava9$1",
      "org.apache.storm.shade.io.netty.util.internal.CleanerJava9",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent$4",
      "org.apache.storm.shade.io.netty.util.internal.PlatformDependent",
      "org.apache.storm.shade.io.netty.util.NetUtil",
      "org.apache.storm.thrift.transport.AutoExpandingBuffer",
      "redis.clients.jedis.HostAndPort"
    );
  }
}
