/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 31 19:01:19 GMT 2026
 */

package org.apache.storm.daemon.ui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import clojure.lang.PersistentArrayMap;
import clojure.lang.PersistentList;
import jakarta.ws.rs.core.Response;
import java.sql.SQLDataException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.ServiceConfigurationError;
import javax.swing.JLayeredPane;
import org.apache.storm.daemon.ui.IConfigurator;
import org.apache.storm.daemon.ui.UIHelpers;
import org.apache.storm.generated.ClusterSummary;
import org.apache.storm.generated.ComponentPageInfo;
import org.apache.storm.generated.ExecutorInfo;
import org.apache.storm.generated.ExecutorSummary;
import org.apache.storm.generated.GlobalStreamId;
import org.apache.storm.generated.Grouping;
import org.apache.storm.generated.LogConfig;
import org.apache.storm.generated.Nimbus;
import org.apache.storm.generated.NodeInfo;
import org.apache.storm.generated.OwnerResourceSummary;
import org.apache.storm.generated.ProfileAction;
import org.apache.storm.generated.ProfileRequest;
import org.apache.storm.generated.SupervisorPageInfo;
import org.apache.storm.generated.SupervisorSummary;
import org.apache.storm.generated.TopologySummary;
import org.apache.storm.thrift.TConfiguration;
import org.apache.storm.thrift.protocol.TCompactProtocol;
import org.apache.storm.thrift.protocol.TJSONProtocol;
import org.apache.storm.thrift.protocol.TProtocol;
import org.apache.storm.thrift.protocol.TSimpleJSONProtocol;
import org.apache.storm.thrift.protocol.TTupleProtocol;
import org.apache.storm.thrift.transport.TMemoryInputTransport;
import org.apache.storm.thrift.transport.TMemoryTransport;
import org.apache.storm.thrift.transport.TTransport;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.FilterHolder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UIHelpers_ESTest extends UIHelpers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Object[] objectArray0 = new Object[2];
      PersistentArrayMap persistentArrayMap0 = new PersistentArrayMap(objectArray0);
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyLogLevel((Nimbus.Iface) null, persistentArrayMap0, "v6$DiVQlI(hh[Cv)");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PersistentArrayMap persistentArrayMap0 = PersistentArrayMap.EMPTY;
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyLogLevel((Nimbus.Iface) null, persistentArrayMap0, "v6$DiVQlI(hh[Cv)");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      String string0 = UIHelpers.getWorkerDumpLink("org.apache.storm.generated.TopologyPageInfo$TopologyPageInfoTupleScheme", 2000, "h-MRSDyGR9~y=4]<", hashMap0);
      assertEquals("http://org.apache.storm.generated.TopologyPageInfo%2524TopologyPageInfoTupleScheme:null/api/v1/dumps/h-MRSDyGR9%257Ey%253D4%255D%253C/org.apache.storm.generated.TopologyPageInfo%2524TopologyPageInfoTupleScheme%3A2000", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ExecutorInfo executorInfo0 = new ExecutorInfo();
      ExecutorSummary executorSummary0 = new ExecutorSummary(executorInfo0, "errorPort", "errorPort", (-241), 80);
      Map<String, Object> map0 = UIHelpers.getStatMapFromExecutorSummary(executorSummary0);
      assertEquals(4, map0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = UIHelpers.sanitizeStreamName("clojure.core$reset_meta_BANG_");
      assertEquals("clojure.core_reset_meta_BANG_", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = UIHelpers.sanitizeStreamName("`:");
      assertEquals("_s__", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = UIHelpers.getWindowHint(":all-time");
      assertEquals("All time", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      // Undeclared exception!
      try { 
        UIHelpers.getLogviewerPort(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      String string0 = UIHelpers.getLogviewerLink("", "", hashMap0, 0);
      assertEquals("http://:null/api/v1/log?file=", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      ArrayList<OwnerResourceSummary> arrayList0 = new ArrayList<OwnerResourceSummary>();
      Map<String, Object> map0 = UIHelpers.getOwnerResourceSummary(arrayList0, (Nimbus.Iface) null, "com.google.common.base.Predicates$ContainsPatternFromStringPredicate", hashMap0);
      assertEquals(18, map0.size());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      Object object0 = new Object();
      PersistentList persistentList0 = new PersistentList(object0);
      TSimpleJSONProtocol tSimpleJSONProtocol0 = new TSimpleJSONProtocol((TTransport) null);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tSimpleJSONProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getOwnerResourceSummary(persistentList0, nimbus_Client0, "la>.>QcSJW.Rk-E", hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.protocol.TSimpleJSONProtocol", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      OwnerResourceSummary ownerResourceSummary0 = new OwnerResourceSummary("#=");
      ownerResourceSummary0.set_memory_guarantee_isSet(true);
      Map<String, Object> map0 = UIHelpers.unpackOwnerResourceSummary(ownerResourceSummary0);
      assertEquals(18, map0.size());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TopologySummary topologySummary0 = new TopologySummary("#oZ8>", "_EA %(iT(GFO4}ESa", 2000, 8232, 0, 0, "#oZ8>");
      Map<String, Object> map0 = UIHelpers.getTopologyMap(topologySummary0);
      // Undeclared exception!
      try { 
        UIHelpers.getClusterSummary((ClusterSummary) null, "_EA %(iT(GFO4}ESa", map0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SQLDataException sQLDataException0 = new SQLDataException("/component.html?id=%s&topology_id=%s");
      Map map0 = UIHelpers.exceptionToJson(sQLDataException0, 1000);
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SQLDataException sQLDataException0 = new SQLDataException("");
      // Undeclared exception!
      try { 
        UIHelpers.exceptionToJson(sQLDataException0, (-2310));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index -2310 out of bounds for length 512
         //
         verifyException("org.eclipse.jetty.http.HttpStatus", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Response.Status response_Status0 = Response.Status.INTERNAL_SERVER_ERROR;
      // Undeclared exception!
      try { 
        UIHelpers.makeStandardResponse((Object) null, "nonHeapMemoryUsage", false, response_Status0);
        fail("Expecting exception: ServiceConfigurationError");
      
      } catch(ServiceConfigurationError e) {
         //
         // jakarta.ws.rs.ext.RuntimeDelegate: org.glassfish.jersey.internal.RuntimeDelegateImpl not a subtype
         //
         verifyException("java.util.ServiceLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String string0 = UIHelpers.getJsonResponseBody((Object) null, (String) null, true);
      assertNotNull(string0);
      assertEquals("null", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Integer integer0 = JLayeredPane.POPUP_LAYER;
      Boolean boolean0 = Boolean.valueOf("$");
      Server server0 = UIHelpers.jettyCreateServer(integer0, "Iv35]I;", integer0, integer0, boolean0);
      assertTrue(server0.isStopped());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Integer integer0 = JLayeredPane.DEFAULT_LAYER;
      Server server0 = UIHelpers.jettyCreateServer(integer0, "http://:null/api/v1/log?file=", integer0, (Boolean) null);
      assertEquals(0L, server0.getStopTimeout());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      OwnerResourceSummary ownerResourceSummary0 = new OwnerResourceSummary("#=");
      Map<String, Object> map0 = UIHelpers.unpackOwnerResourceSummary(ownerResourceSummary0);
      String string0 = UIHelpers.getNimbusLogLink("mcFj&< 1KQk-0s~", map0);
      assertEquals("http://mcFj%26%3C+1KQk-0s%7E:null/api/v1/daemonlog?file=nimbus.log", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      SupervisorPageInfo supervisorPageInfo0 = new SupervisorPageInfo();
      // Undeclared exception!
      try { 
        UIHelpers.getSupervisorPageInfo(supervisorPageInfo0, hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingDumpJstack((Nimbus.Iface) null, "E", (String) null, (Map<String, Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        UIHelpers.makeStandardResponse(object0, "zCoi+AM'p7");
        fail("Expecting exception: ServiceConfigurationError");
      
      } catch(ServiceConfigurationError e) {
         //
         // jakarta.ws.rs.ext.RuntimeDelegate: org.glassfish.jersey.internal.RuntimeDelegateImpl not a subtype
         //
         verifyException("java.util.ServiceLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ExecutorInfo executorInfo0 = new ExecutorInfo(662, 662);
      String string0 = UIHelpers.prettyExecutorInfo(executorInfo0);
      assertEquals("[662-662]", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      FilterHolder filterHolder0 = UIHelpers.mkAccessLoggingFilterHandle();
      assertFalse(filterHolder0.isStopping());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      OwnerResourceSummary ownerResourceSummary0 = new OwnerResourceSummary();
      Map<String, Object> map0 = UIHelpers.unpackOwnerResourceSummary(ownerResourceSummary0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client((TProtocol) null, (TProtocol) null);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingDump(nimbus_Client0, "", "nO;UoBAF&NJldq!G", map0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.getProfilingDisabled();
      SupervisorSummary supervisorSummary0 = new SupervisorSummary();
      // Undeclared exception!
      try { 
        UIHelpers.getPrettifiedSupervisorMap(supervisorSummary0, map0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.prettyUptimeMs("U]Oh88%k<^Asz8304");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"U]Oh88%k<^Asz8304\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TTupleProtocol tTupleProtocol0 = new TTupleProtocol((TTransport) null);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tTupleProtocol0, tTupleProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyDeactivate(nimbus_Client0, "/component.html?id=%s&topology_id=%s");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.protocol.TCompactProtocol", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Nimbus.Client nimbus_Client0 = new Nimbus.Client((TProtocol) null, (TProtocol) null);
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyDebugActionSpct(nimbus_Client0, "uh.0J.'oQ3\\C^", " wN!c", " wN!c", " wN!c");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.TServiceClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ComponentPageInfo componentPageInfo0 = new ComponentPageInfo();
      // Undeclared exception!
      try { 
        UIHelpers.unpackSpoutPageInfo(componentPageInfo0, "z", "*compile-files*", true, componentPageInfo0.metaDataMap);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      IConfigurator iConfigurator0 = mock(IConfigurator.class, new ViolatedAssumptionAnswer());
      try { 
        UIHelpers.stormRunJetty((Integer) null, (Integer) null, iConfigurator0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("org.evosuite.runtime.mock.java.lang.MockException", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.getTopologyOpResponse("/component.html?id=%s&topology_id=%s", "?>");
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      UIHelpers uIHelpers0 = new UIHelpers();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyActivate((Nimbus.Iface) null, "totalMem");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      FilterHolder filterHolder0 = UIHelpers.corsFilterHandle();
      //  // Unstable assertion: assertEquals("org.eclipse.jetty.servlets.CrossOriginFilter-9", filterHolder0.getName());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ComponentPageInfo componentPageInfo0 = new ComponentPageInfo();
      // Undeclared exception!
      try { 
        UIHelpers.unpackBoltPageInfo(componentPageInfo0, "", "", false, componentPageInfo0.metaDataMap);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.getWindowHint("");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ExecutorSummary executorSummary0 = new ExecutorSummary();
      Nimbus.Client nimbus_Client0 = new Nimbus.Client((TProtocol) null, (TProtocol) null);
      // Undeclared exception!
      try { 
        UIHelpers.getActiveProfileActions(nimbus_Client0, "eventLogLink", "eventLogLink", executorSummary0.metaDataMap);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.TServiceClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.getInputMap((Map.Entry<GlobalStreamId, Grouping>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      LogConfig logConfig0 = new LogConfig();
      Map<String, Object> map0 = UIHelpers.getTopolgoyLogConfig(logConfig0);
      TConfiguration tConfiguration0 = TConfiguration.DEFAULT;
      TMemoryInputTransport tMemoryInputTransport0 = new TMemoryInputTransport(tConfiguration0);
      TCompactProtocol tCompactProtocol0 = new TCompactProtocol(tMemoryInputTransport0, (-1469L), 64);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tCompactProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingStop(nimbus_Client0, "Content-Type", "qCf#^M/4L", map0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      TopologySummary topologySummary0 = new TopologySummary("^sZz0r3nt A:;P1!", ":type", 1182, (-647), 0, 24, "=^4o2dk");
      Map<String, Object> map0 = UIHelpers.getTopologyMap(topologySummary0);
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Nimbus.Client nimbus_Client0 = new Nimbus.Client((TProtocol) null);
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyKill(nimbus_Client0, "jdk_version", "jdk_version");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.TServiceClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      TConfiguration tConfiguration0 = new TConfiguration();
      byte[] byteArray0 = new byte[8];
      TMemoryTransport tMemoryTransport0 = new TMemoryTransport(tConfiguration0, byteArray0);
      TJSONProtocol tJSONProtocol0 = new TJSONProtocol(tMemoryTransport0, false);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tJSONProtocol0, tJSONProtocol0);
      try { 
        UIHelpers.putTopologyRebalance(nimbus_Client0, "more", "[{}]");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Unexpected character:\u0000
         //
         verifyException("org.apache.storm.thrift.protocol.TJSONProtocol", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      OwnerResourceSummary ownerResourceSummary0 = new OwnerResourceSummary();
      Map<String, Object> map0 = UIHelpers.unpackOwnerResourceSummary(ownerResourceSummary0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client((TProtocol) null, (TProtocol) null);
      // Undeclared exception!
      try { 
        UIHelpers.getBuildVisualization(nimbus_Client0, map0, "/0Yc/ [/QI$+NiJfifN", "logviewer.https.port", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.TServiceClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      NodeInfo nodeInfo0 = new NodeInfo();
      ProfileAction profileAction0 = ProfileAction.JMAP_DUMP;
      ProfileRequest profileRequest0 = new ProfileRequest(nodeInfo0, profileAction0);
      // Undeclared exception!
      try { 
        UIHelpers.getActiveAction(profileRequest0, profileRequest0.metaDataMap, "?`DAm3HO_#<");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Integer integer0 = JLayeredPane.POPUP_LAYER;
      Boolean boolean0 = Boolean.TRUE;
      Server server0 = UIHelpers.jettyCreateServer(integer0, "/component.html?id=%s&topology_id=%s", integer0, boolean0);
      assertFalse(server0.isDryRun());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.unauthorizedUserJson("-P`sB/3!v'");
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingDumpHeap((Nimbus.Iface) null, "lbqnC;*", (String) null, map0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }
}
