/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 31 15:53:10 GMT 2026
 */

package org.apache.storm.daemon.ui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import clojure.lang.IPersistentMap;
import clojure.lang.MapEntry;
import clojure.lang.PersistentHashMap;
import io.dropwizard.jersey.DropwizardResourceConfig;
import jakarta.ws.rs.core.Response;
import java.sql.BatchUpdateException;
import java.sql.SQLSyntaxErrorException;
import java.util.Map;
import java.util.ServiceConfigurationError;
import java.util.Set;
import java.util.TreeMap;
import java.util.concurrent.ConcurrentHashMap;
import javax.swing.JLayeredPane;
import org.apache.storm.daemon.ui.IConfigurator;
import org.apache.storm.daemon.ui.UIHelpers;
import org.apache.storm.generated.ComponentPageInfo;
import org.apache.storm.generated.ComponentType;
import org.apache.storm.generated.ExecutorInfo;
import org.apache.storm.generated.ExecutorSummary;
import org.apache.storm.generated.LogConfig;
import org.apache.storm.generated.Nimbus;
import org.apache.storm.generated.NodeInfo;
import org.apache.storm.generated.OwnerResourceSummary;
import org.apache.storm.generated.ProfileAction;
import org.apache.storm.generated.ProfileRequest;
import org.apache.storm.generated.SupervisorPageInfo;
import org.apache.storm.generated.TopologyHistoryInfo;
import org.apache.storm.generated.TopologySummary;
import org.apache.storm.thrift.TConfiguration;
import org.apache.storm.thrift.protocol.TBinaryProtocol;
import org.apache.storm.thrift.protocol.TCompactProtocol;
import org.apache.storm.thrift.protocol.TJSONProtocol;
import org.apache.storm.thrift.protocol.TMultiplexedProtocol;
import org.apache.storm.thrift.protocol.TProtocol;
import org.apache.storm.thrift.protocol.TTupleProtocol;
import org.apache.storm.thrift.transport.AutoExpandingBufferWriteTransport;
import org.apache.storm.thrift.transport.TMemoryBuffer;
import org.apache.storm.thrift.transport.TMemoryInputTransport;
import org.apache.storm.thrift.transport.TTransport;
import org.eclipse.jetty.io.EofException;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.FilterHolder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.glassfish.hk2.utilities.NamedImpl;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UIHelpers_ESTest extends UIHelpers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LogConfig logConfig0 = new LogConfig();
      Map<String, Object> map0 = UIHelpers.getTopolgoyLogConfig(logConfig0);
      String string0 = UIHelpers.getWorkerDumpLink("2ku", (-27L), "4mNuLlNd.l`W=", map0);
      assertEquals("http://2ku:null/api/v1/dumps/4mNuLlNd.l%2560W%253D/2ku%3A-27", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ExecutorInfo executorInfo0 = new ExecutorInfo();
      ExecutorSummary executorSummary0 = new ExecutorSummary(executorInfo0, (String) null, "^glN]BwDz8KoQ+k'8", (-986), (-2120));
      Map<String, Object> map0 = UIHelpers.getStatMapFromExecutorSummary(executorSummary0);
      assertEquals(4, map0.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Object[] objectArray0 = new Object[2];
      PersistentHashMap persistentHashMap0 = PersistentHashMap.create((IPersistentMap) null, objectArray0);
      // Undeclared exception!
      try { 
        UIHelpers.sanitizeTransferredStats(persistentHashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PersistentHashMap persistentHashMap0 = PersistentHashMap.EMPTY;
      Map<String, Map<String, Long>> map0 = UIHelpers.sanitizeTransferredStats(persistentHashMap0);
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = UIHelpers.sanitizeStreamName("}gGb{");
      assertEquals("_s_gGb_", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = UIHelpers.sanitizeStreamName("gGS");
      assertEquals("gGS", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TopologySummary topologySummary0 = new TopologySummary("J4ULgkOs!bmZ907V!u", "oQF_/b", 104857600, (-2021161078), 24, 104857600, "componntype");
      Map<String, Object> map0 = UIHelpers.getTopologyMap(topologySummary0);
      String string0 = UIHelpers.getSupervisorLogLink(":all-time", map0);
      assertEquals("http://%3Aall-time:null/api/v1/daemonlog?file=supervisor.log", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int[] intArray0 = new int[1];
      EofException eofException0 = new EofException("%`m~Z");
      BatchUpdateException batchUpdateException0 = new BatchUpdateException(intArray0, eofException0);
      SQLSyntaxErrorException sQLSyntaxErrorException0 = new SQLSyntaxErrorException("%`m~Z", "%`m~Z", batchUpdateException0);
      Map map0 = UIHelpers.exceptionToJson(sQLSyntaxErrorException0, 2049);
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ComponentPageInfo componentPageInfo0 = new ComponentPageInfo();
      Map map0 = UIHelpers.getJsonResponseHeaders("/BJ+PsJ&[afKG1~", componentPageInfo0.metaDataMap);
      assertEquals(21, map0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Object object0 = new Object();
      Response.Status response_Status0 = Response.Status.SEE_OTHER;
      // Undeclared exception!
      try { 
        UIHelpers.makeStandardResponse(object0, "ints", response_Status0);
        fail("Expecting exception: ServiceConfigurationError");
      
      } catch(ServiceConfigurationError e) {
         //
         // jakarta.ws.rs.ext.RuntimeDelegate: org.glassfish.jersey.internal.RuntimeDelegateImpl not a subtype
         //
         verifyException("java.util.ServiceLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        UIHelpers.getJsonResponseBody(object0, "$", false);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.Object cannot be cast to class java.lang.String (java.lang.Object and java.lang.String are in module java.base of loader 'bootstrap')
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Integer integer0 = JLayeredPane.FRAME_CONTENT_LAYER;
      Integer integer1 = JLayeredPane.PALETTE_LAYER;
      Boolean boolean0 = Boolean.valueOf(false);
      Server server0 = UIHelpers.jettyCreateServer(integer0, "$", integer1, boolean0);
      assertFalse(server0.isDumpBeforeStop());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = JLayeredPane.FRAME_CONTENT_LAYER;
      Boolean boolean0 = Boolean.valueOf(false);
      Server server0 = UIHelpers.jettyCreateServer(integer0, "", integer0, boolean0);
      assertEquals("11.0.24", server0.getVersion());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PersistentHashMap persistentHashMap0 = PersistentHashMap.EMPTY;
      // Undeclared exception!
      try { 
        UIHelpers.getSupervisorPageInfo((SupervisorPageInfo) null, persistentHashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TopologySummary topologySummary0 = new TopologySummary("componentType", "org.glassfish.jersey.message.internal.CommittingOutputStream", 248, 248, 248, 248, (String) null);
      Map<String, Object> map0 = UIHelpers.getTopologyMap(topologySummary0);
      String string0 = UIHelpers.getWorkerLogLink("http://BMt%22%7Du%3An+Uf:null/api/v1/daemonlog?file=supervisor.log", 248, map0, "componentType");
      assertEquals("http://http%3A%2F%2FBMt%2522%257Du%253An%2BUf%3Anull%2Fapi%2Fv1%2Fdaemonlog%3Ffile%3Dsupervisor.log:null/api/v1/log?file=componentType%5C248%5Cworker.log", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      NamedImpl namedImpl0 = new NamedImpl("1]nQ");
      // Undeclared exception!
      try { 
        UIHelpers.makeStandardResponse((Object) namedImpl0, "1]nQ");
        fail("Expecting exception: ServiceConfigurationError");
      
      } catch(ServiceConfigurationError e) {
         //
         // jakarta.ws.rs.ext.RuntimeDelegate: org.glassfish.jersey.internal.RuntimeDelegateImpl not a subtype
         //
         verifyException("java.util.ServiceLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ExecutorInfo executorInfo0 = new ExecutorInfo(3598, 573);
      String string0 = UIHelpers.prettyExecutorInfo(executorInfo0);
      assertEquals("[3598-573]", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FilterHolder filterHolder0 = UIHelpers.mkAccessLoggingFilterHandle();
      assertTrue(filterHolder0.isStopped());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TopologyHistoryInfo topologyHistoryInfo0 = new TopologyHistoryInfo();
      Map<String, Object> map0 = UIHelpers.getTopologyHistoryInfo(topologyHistoryInfo0);
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DropwizardResourceConfig dropwizardResourceConfig0 = new DropwizardResourceConfig();
      Map<String, Object> map0 = dropwizardResourceConfig0.getProperties();
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingDump((Nimbus.Iface) null, "98i#Mg", (String) null, map0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.getProfilingDisabled();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.prettyUptimeMs("Ue7K ");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"Ue7K \"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      TMemoryInputTransport tMemoryInputTransport0 = new TMemoryInputTransport(byteArray0, (byte) (-56), (byte)0);
      TJSONProtocol tJSONProtocol0 = new TJSONProtocol(tMemoryInputTransport0, false);
      TMultiplexedProtocol tMultiplexedProtocol0 = new TMultiplexedProtocol(tJSONProtocol0, "openStream");
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tMultiplexedProtocol0, tJSONProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyDeactivate(nimbus_Client0, "");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // No writing allowed!
         //
         verifyException("org.apache.storm.thrift.transport.TMemoryInputTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TopologyHistoryInfo topologyHistoryInfo0 = new TopologyHistoryInfo();
      ComponentType componentType0 = ComponentType.BOLT;
      ComponentPageInfo componentPageInfo0 = new ComponentPageInfo("FAILED", componentType0);
      // Undeclared exception!
      try { 
        UIHelpers.unpackSpoutPageInfo(componentPageInfo0, "STOPPED", "STARTED", false, topologyHistoryInfo0.metaDataMap);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Integer integer0 = JLayeredPane.POPUP_LAYER;
      IConfigurator iConfigurator0 = mock(IConfigurator.class, new ViolatedAssumptionAnswer());
      try { 
        UIHelpers.stormRunJetty(integer0, integer0, iConfigurator0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("org.evosuite.runtime.mock.java.lang.MockException", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.getTopologyOpResponse("J4ULgkOs!bmZ907V!u", "BMt\"}u:n Uf");
      assertEquals(3, map0.size());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyActivate((Nimbus.Iface) null, "org.apache.storm.generated.Nimbus$getTopologySummaryByName_result$getTopologySummaryByName_resultStandardScheme");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      FilterHolder filterHolder0 = UIHelpers.corsFilterHandle();
      //  // Unstable assertion: assertEquals("org.eclipse.jetty.servlets.CrossOriginFilter-9", filterHolder0.getName());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ComponentType componentType0 = ComponentType.SPOUT;
      ComponentPageInfo componentPageInfo0 = new ComponentPageInfo((String) null, componentType0);
      // Undeclared exception!
      try { 
        UIHelpers.unpackBoltPageInfo(componentPageInfo0, (String) null, ":transferred", false, componentPageInfo0.metaDataMap);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      String string0 = UIHelpers.prettyUptimeMs(0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.getWindowHint("componentType");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"componentType\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MapEntry mapEntry0 = new MapEntry("^", "^");
      // Undeclared exception!
      try { 
        UIHelpers.getInputMap(mapEntry0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.String cannot be cast to class org.apache.storm.generated.GlobalStreamId (java.lang.String is in module java.base of loader 'bootstrap'; org.apache.storm.generated.GlobalStreamId is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @3c7a2018)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TreeMap<String, Object> treeMap0 = new TreeMap<String, Object>();
      TCompactProtocol tCompactProtocol0 = new TCompactProtocol((TTransport) null);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tCompactProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingStop(nimbus_Client0, "STOPPED", "!1dpN", treeMap0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      OwnerResourceSummary ownerResourceSummary0 = new OwnerResourceSummary(",zi!");
      Map<String, Object> map0 = UIHelpers.unpackOwnerResourceSummary(ownerResourceSummary0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client((TProtocol) null, (TProtocol) null);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingDumpJstack(nimbus_Client0, "[3598-573]", "volatile!", map0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TopologySummary topologySummary0 = new TopologySummary("J4ULgkOs!bmZ907V!u", "oQF_/b", 104857600, (-2021161078), 24, 104857600, "componntype");
      Map<String, Object> map0 = UIHelpers.getTopologyMap(topologySummary0);
      String string0 = UIHelpers.getNimbusLogLink("$", map0);
      assertEquals("http://%24:null/api/v1/daemonlog?file=nimbus.log", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      TConfiguration tConfiguration0 = new TConfiguration(795, 2780, 0);
      byte[] byteArray0 = new byte[6];
      TMemoryInputTransport tMemoryInputTransport0 = new TMemoryInputTransport(tConfiguration0, byteArray0, 2373, (byte)36);
      TBinaryProtocol tBinaryProtocol0 = new TBinaryProtocol(tMemoryInputTransport0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tBinaryProtocol0, tBinaryProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyKill(nimbus_Client0, (String) null, (String) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // No writing allowed!
         //
         verifyException("org.apache.storm.thrift.transport.TMemoryInputTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      TJSONProtocol tJSONProtocol0 = new TJSONProtocol((TTransport) null);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tJSONProtocol0, tJSONProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyRebalance(nimbus_Client0, "$", "UR88a6(*");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.protocol.TJSONProtocol", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      TConfiguration tConfiguration0 = TConfiguration.DEFAULT;
      TMemoryBuffer tMemoryBuffer0 = new TMemoryBuffer(tConfiguration0, 526);
      TBinaryProtocol tBinaryProtocol0 = new TBinaryProtocol(tMemoryBuffer0);
      TMultiplexedProtocol tMultiplexedProtocol0 = new TMultiplexedProtocol(tBinaryProtocol0, "deactivate");
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tMultiplexedProtocol0);
      try { 
        UIHelpers.getBuildVisualization(nimbus_Client0, (Map<String, Object>) null, (String) null, (String) null, false);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Required field 'msg' is unset! Struct:AuthorizationException(msg:null)
         //
         verifyException("org.apache.storm.generated.AuthorizationException", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ConcurrentHashMap<String, Object> concurrentHashMap0 = new ConcurrentHashMap<String, Object>();
      NodeInfo nodeInfo0 = new NodeInfo("^", (Set<Long>) null);
      ProfileAction profileAction0 = ProfileAction.JMAP_DUMP;
      ProfileRequest profileRequest0 = new ProfileRequest(nodeInfo0, profileAction0);
      // Undeclared exception!
      try { 
        UIHelpers.getActiveAction(profileRequest0, concurrentHashMap0, "^");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      TConfiguration tConfiguration0 = TConfiguration.DEFAULT;
      Server server0 = UIHelpers.jettyCreateServer((Integer) tConfiguration0.DEFAULT_MAX_MESSAGE_SIZE, "J4ULgkOs!bmZ907V!u", (Integer) 64, (Boolean) null);
      assertFalse(server0.isDumpAfterStart());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.unauthorizedUserJson("");
      TConfiguration tConfiguration0 = TConfiguration.DEFAULT;
      AutoExpandingBufferWriteTransport autoExpandingBufferWriteTransport0 = new AutoExpandingBufferWriteTransport(tConfiguration0, 16384000, 64);
      TTupleProtocol tTupleProtocol0 = new TTupleProtocol(autoExpandingBufferWriteTransport0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tTupleProtocol0, tTupleProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getActiveProfileActions(nimbus_Client0, "", "", map0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.transport.AutoExpandingBufferWriteTransport", e);
      }
  }
}
