/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 31 20:51:05 GMT 2026
 */

package org.apache.storm.redis.bolt;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.storm.redis.bolt.RedisFilterBolt;
import org.apache.storm.redis.common.config.JedisClusterConfig;
import org.apache.storm.redis.common.config.JedisPoolConfig;
import org.apache.storm.redis.common.mapper.RedisDataTypeDescription;
import org.apache.storm.redis.common.mapper.RedisFilterMapper;
import org.apache.storm.topology.OutputFieldsGetter;
import org.apache.storm.tuple.Tuple;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RedisFilterBolt_ESTest extends RedisFilterBolt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.LIST;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("wK").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("wK").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      JedisClusterConfig jedisClusterConfig0 = new JedisClusterConfig();
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisClusterConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.GEO;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("Missing limit node for quota {}").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("Missing limit node for quota {}").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      JedisClusterConfig jedisClusterConfig0 = new JedisClusterConfig();
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisClusterConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.SORTED_SET;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      JedisClusterConfig jedisClusterConfig0 = new JedisClusterConfig();
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisClusterConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig();
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.HASH;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("l{EKS ;+) NS1< ").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("l{EKS ;+) NS1< ").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.SET;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      JedisClusterConfig jedisClusterConfig0 = new JedisClusterConfig();
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisClusterConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig();
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.HYPER_LOG_LOG;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("Missing limit node for quota {}").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("Missing limit node for quota {}").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig();
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.STRING;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("Missing limit node for quota {}").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("Missing limit node for quota {}").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig();
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.SET;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
      OutputFieldsGetter outputFieldsGetter0 = new OutputFieldsGetter();
      redisFilterBolt0.declareOutputFields(outputFieldsGetter0);
  }
}
