/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 31 14:40:58 GMT 2026
 */

package org.apache.storm.daemon.ui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import clojure.lang.APersistentMap;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.PersistentArrayMap;
import clojure.lang.PersistentHashMap;
import clojure.lang.PersistentVector;
import jakarta.ws.rs.core.Response;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.nio.ByteBuffer;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import java.util.ServiceConfigurationError;
import java.util.TreeMap;
import java.util.concurrent.ConcurrentHashMap;
import javax.swing.JLayeredPane;
import org.apache.storm.daemon.ui.IConfigurator;
import org.apache.storm.daemon.ui.UIHelpers;
import org.apache.storm.generated.ComponentPageInfo;
import org.apache.storm.generated.ExecutorInfo;
import org.apache.storm.generated.ExecutorSummary;
import org.apache.storm.generated.LogConfig;
import org.apache.storm.generated.Nimbus;
import org.apache.storm.generated.OwnerResourceSummary;
import org.apache.storm.generated.SupervisorSummary;
import org.apache.storm.generated.TopologyHistoryInfo;
import org.apache.storm.generated.TopologyPageInfo;
import org.apache.storm.thrift.TConfiguration;
import org.apache.storm.thrift.protocol.TBinaryProtocol;
import org.apache.storm.thrift.protocol.TCompactProtocol;
import org.apache.storm.thrift.protocol.TJSONProtocol;
import org.apache.storm.thrift.protocol.TProtocol;
import org.apache.storm.thrift.protocol.TSimpleJSONProtocol;
import org.apache.storm.thrift.transport.AutoExpandingBufferReadTransport;
import org.apache.storm.thrift.transport.TByteBuffer;
import org.apache.storm.thrift.transport.TIOStreamTransport;
import org.apache.storm.thrift.transport.TMemoryBuffer;
import org.apache.storm.thrift.transport.TMemoryInputTransport;
import org.apache.storm.thrift.transport.TSimpleFileTransport;
import org.apache.storm.thrift.transport.TSocket;
import org.apache.storm.thrift.transport.TTransport;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.FilterHolder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.glassfish.hk2.utilities.UnqualifiedImpl;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UIHelpers_ESTest extends UIHelpers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LogConfig logConfig0 = new LogConfig();
      Map<String, Object> map0 = UIHelpers.getTopolgoyLogConfig(logConfig0);
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PersistentHashMap persistentHashMap0 = PersistentHashMap.EMPTY;
      String string0 = UIHelpers.getWorkerDumpLink("AW5NTzaBi.[s", 43L, "AW5NTzaBi.[s", persistentHashMap0);
      assertEquals("http://AW5NTzaBi.%255Bs:null/api/v1/dumps/AW5NTzaBi.%255Bs/AW5NTzaBi.%255Bs%3A43", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = UIHelpers.sanitizeStreamName("hibernate.validator.locale_resolver");
      assertEquals("hibernate.validator.locale_resolver", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = UIHelpers.sanitizeStreamName("`:");
      assertEquals("_s__", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TreeMap<String, Double> treeMap0 = new TreeMap<String, Double>();
      Map<String, Double> map0 = UIHelpers.getStatDisplayMap(treeMap0);
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = UIHelpers.getWindowHint(":all-time");
      assertEquals("All time", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Object[] objectArray0 = new Object[3];
      PersistentVector persistentVector0 = PersistentVector.create(objectArray0);
      TSimpleJSONProtocol tSimpleJSONProtocol0 = new TSimpleJSONProtocol((TTransport) null);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tSimpleJSONProtocol0, tSimpleJSONProtocol0);
      PersistentArrayMap persistentArrayMap0 = new PersistentArrayMap(objectArray0);
      // Undeclared exception!
      try { 
        UIHelpers.getOwnerResourceSummary(persistentVector0, nimbus_Client0, "}fEnk,ka (!vFM}", persistentArrayMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.protocol.TSimpleJSONProtocol", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Boolean boolean0 = Boolean.valueOf(true);
      Integer integer0 = JLayeredPane.FRAME_CONTENT_LAYER;
      Integer integer1 = JLayeredPane.MODAL_LAYER;
      Server server0 = UIHelpers.jettyCreateServer(integer0, "clojure.pprint$set_pprint_dispatch", integer1, integer0, boolean0);
      assertFalse(server0.isStarting());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Integer integer0 = JLayeredPane.FRAME_CONTENT_LAYER;
      Boolean boolean0 = Boolean.valueOf(false);
      Server server0 = UIHelpers.jettyCreateServer(integer0, "STOPPED", integer0, integer0, boolean0);
      assertEquals(0L, server0.getStopTimeout());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SupervisorSummary supervisorSummary0 = new SupervisorSummary();
      PersistentHashMap persistentHashMap0 = PersistentHashMap.createWithCheck((ISeq) null);
      // Undeclared exception!
      try { 
        UIHelpers.getPrettifiedSupervisorMap(supervisorSummary0, persistentHashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Object[] objectArray0 = new Object[2];
      PersistentArrayMap persistentArrayMap0 = PersistentArrayMap.createWithCheck(objectArray0);
      String string0 = UIHelpers.getWorkerLogLink("&+(!@a0/`", 517, persistentArrayMap0, "nl!Lzu");
      assertEquals("http://%26%2B%28%21%40a0%2F%60:null/api/v1/log?file=nl%21Lzu%5C517%5Cworker.log", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = UIHelpers.prettyUptimeSec(4);
      assertEquals("4s", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      byte[] byteArray0 = new byte[7];
      ByteBuffer byteBuffer0 = ByteBuffer.wrap(byteArray0);
      TByteBuffer tByteBuffer0 = new TByteBuffer(byteBuffer0);
      TJSONProtocol tJSONProtocol0 = new TJSONProtocol(tByteBuffer0, true);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tJSONProtocol0, tJSONProtocol0);
      Object[] objectArray0 = new Object[3];
      Object object0 = new Object();
      objectArray0[0] = object0;
      PersistentArrayMap persistentArrayMap0 = PersistentArrayMap.createWithCheck(objectArray0);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingDumpJstack(nimbus_Client0, (String) null, "", persistentArrayMap0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ExecutorSummary executorSummary0 = new ExecutorSummary();
      // Undeclared exception!
      try { 
        UIHelpers.makeStandardResponse((Object) executorSummary0, (String) null);
        fail("Expecting exception: ServiceConfigurationError");
      
      } catch(ServiceConfigurationError e) {
         //
         // jakarta.ws.rs.ext.RuntimeDelegate: org.glassfish.jersey.internal.RuntimeDelegateImpl not a subtype
         //
         verifyException("java.util.ServiceLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ExecutorInfo executorInfo0 = new ExecutorInfo((-1945), (-1945));
      String string0 = UIHelpers.prettyExecutorInfo(executorInfo0);
      assertEquals("[-1945--1945]", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TopologyPageInfo topologyPageInfo0 = new TopologyPageInfo((String) null);
      Object[] objectArray0 = new Object[4];
      objectArray0[2] = (Object) "";
      PersistentHashMap persistentHashMap0 = PersistentHashMap.createWithCheck(objectArray0);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologySummary(topologyPageInfo0, "", persistentHashMap0, "certificate not valid till ");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FilterHolder filterHolder0 = UIHelpers.mkAccessLoggingFilterHandle();
      assertFalse(filterHolder0.isStarted());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PersistentArrayMap persistentArrayMap0 = PersistentArrayMap.EMPTY;
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingDumpHeap((Nimbus.Iface) null, "&{", ">$fEv+HHh", persistentArrayMap0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Response.Status response_Status0 = Response.Status.GATEWAY_TIMEOUT;
      // Undeclared exception!
      try { 
        UIHelpers.makeStandardResponse((Object) null, "", response_Status0);
        fail("Expecting exception: ServiceConfigurationError");
      
      } catch(ServiceConfigurationError e) {
         //
         // jakarta.ws.rs.ext.RuntimeDelegate: org.glassfish.jersey.internal.RuntimeDelegateImpl not a subtype
         //
         verifyException("java.util.ServiceLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyHistoryInfo((TopologyHistoryInfo) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TConfiguration tConfiguration0 = new TConfiguration();
      TMemoryBuffer tMemoryBuffer0 = new TMemoryBuffer(tConfiguration0, 1586);
      TCompactProtocol tCompactProtocol0 = new TCompactProtocol(tMemoryBuffer0, 1464L, 986L);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tCompactProtocol0);
      TreeMap<String, Object> treeMap0 = new TreeMap<String, Object>();
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingDump(nimbus_Client0, "", "&`.rk0HQ,Oh,", treeMap0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TConfiguration tConfiguration0 = new TConfiguration(2765, (-354), 1879);
      TSocket tSocket0 = new TSocket(tConfiguration0, "YjuPe: 6,[a", (-820), 64);
      TCompactProtocol tCompactProtocol0 = new TCompactProtocol(tSocket0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tCompactProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingStart(nimbus_Client0, "logviewer.https.port", "logviewer.https.port", "YjuPe: 6,[a", (Map<String, Object>) null);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"YjuPe: 6,[a\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.getProfilingDisabled();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.prettyUptimeMs("z/.kx^%.}d-H}(p,T~");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"z/.kx^%.}d-H}(p,T~\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Nimbus.Client nimbus_Client0 = new Nimbus.Client((TProtocol) null, (TProtocol) null);
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyDeactivate(nimbus_Client0, "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.TServiceClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyDebugActionSpct((Nimbus.Iface) null, "T&oJ4WiI9S#`-4Q", "_7Q>E5)V@FPeue}z{y ", "T&oJ4WiI9S#`-4Q", "logviewer.https.port");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Hashtable<UnqualifiedImpl, String> hashtable0 = new Hashtable<UnqualifiedImpl, String>();
      // Undeclared exception!
      try { 
        UIHelpers.unpackSpoutPageInfo((ComponentPageInfo) null, "HA", "logviewer.https.port", false, hashtable0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Integer integer0 = JLayeredPane.DRAG_LAYER;
      IConfigurator iConfigurator0 = mock(IConfigurator.class, new ViolatedAssumptionAnswer());
      try { 
        UIHelpers.stormRunJetty(integer0, integer0, iConfigurator0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("org.evosuite.runtime.mock.java.lang.MockException", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.getTopologyOpResponse("co", "co");
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      UIHelpers uIHelpers0 = new UIHelpers();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ComponentPageInfo componentPageInfo0 = new ComponentPageInfo();
      // Undeclared exception!
      try { 
        UIHelpers.unpackBoltPageInfo(componentPageInfo0, "", "", false, componentPageInfo0.metaDataMap);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      String string0 = UIHelpers.prettyUptimeMs(61);
      assertEquals("61ms", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.getWindowHint("AW5NTzaBi.[s");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"AW5NTzaBi.[s\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      TSimpleJSONProtocol tSimpleJSONProtocol0 = new TSimpleJSONProtocol((TTransport) null);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tSimpleJSONProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getActiveProfileActions(nimbus_Client0, "", "N/A", hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.protocol.TSimpleJSONProtocol", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Object[] objectArray0 = new Object[2];
      PersistentArrayMap persistentArrayMap0 = PersistentArrayMap.createWithCheck(objectArray0);
      TSimpleFileTransport tSimpleFileTransport0 = new TSimpleFileTransport("STOPPING", true, true, false);
      TCompactProtocol tCompactProtocol0 = new TCompactProtocol(tSimpleFileTransport0, 517, 517);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tCompactProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingStop(nimbus_Client0, "", "logviewer.https.port", persistentArrayMap0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      TConfiguration tConfiguration0 = TConfiguration.DEFAULT;
      byte[] byteArray0 = new byte[0];
      TMemoryInputTransport tMemoryInputTransport0 = new TMemoryInputTransport(tConfiguration0, byteArray0, (-2560), 64);
      TJSONProtocol tJSONProtocol0 = new TJSONProtocol(tMemoryInputTransport0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tJSONProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingRestartWorker(nimbus_Client0, "logviewer.https.port", "", hashMap0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      OwnerResourceSummary ownerResourceSummary0 = new OwnerResourceSummary("co");
      Map<String, Object> map0 = UIHelpers.unpackOwnerResourceSummary(ownerResourceSummary0);
      PersistentArrayMap persistentArrayMap0 = PersistentArrayMap.EMPTY;
      Object[] objectArray0 = new Object[8];
      PersistentHashMap persistentHashMap0 = PersistentHashMap.create((IPersistentMap) persistentArrayMap0, objectArray0);
      APersistentMap.KeySeq aPersistentMap_KeySeq0 = APersistentMap.KeySeq.createFromMap(persistentHashMap0);
      // Undeclared exception!
      try { 
        UIHelpers.getAllTopologiesSummary(aPersistentMap_KeySeq0, map0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      TConfiguration tConfiguration0 = new TConfiguration();
      AutoExpandingBufferReadTransport autoExpandingBufferReadTransport0 = new AutoExpandingBufferReadTransport(tConfiguration0, 60);
      TBinaryProtocol tBinaryProtocol0 = new TBinaryProtocol(autoExpandingBufferReadTransport0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tBinaryProtocol0, tBinaryProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyKill(nimbus_Client0, "disabled", "IF_UNMODIFIED_SINCE");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.thrift.transport.AutoExpandingBufferReadTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyRebalance((Nimbus.Iface) null, (String) null, "clojure.lang.ILookupThunk");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      PipedInputStream pipedInputStream0 = new PipedInputStream(pipedOutputStream0);
      TIOStreamTransport tIOStreamTransport0 = new TIOStreamTransport((TConfiguration) null, pipedInputStream0, pipedOutputStream0);
      TCompactProtocol tCompactProtocol0 = new TCompactProtocol(tIOStreamTransport0, (-590L), (-590L));
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tCompactProtocol0, tCompactProtocol0);
      ConcurrentHashMap<String, Object> concurrentHashMap0 = new ConcurrentHashMap<String, Object>();
      try { 
        UIHelpers.getBuildVisualization(nimbus_Client0, concurrentHashMap0, (String) null, "logviewer.https.port", false);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Length exceeded max allowed: 23
         //
         verifyException("org.apache.storm.thrift.protocol.TCompactProtocol", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      String string0 = UIHelpers.getJsonResponseBody("$", "$", false);
      assertEquals("$($);", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Integer integer0 = JLayeredPane.POPUP_LAYER;
      Server server0 = UIHelpers.jettyCreateServer(integer0, "v!kxUky", integer0, (Boolean) null);
      assertEquals(0L, server0.getStopTimeout());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.unauthorizedUserJson("N{DIG3i!1");
      assertEquals(2, map0.size());
  }
}
