/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 23 20:45:59 GMT 2026
 */

package org.apache.storm.redis.bolt;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.InetSocketAddress;
import java.util.HashSet;
import org.apache.storm.redis.bolt.RedisFilterBolt;
import org.apache.storm.redis.common.config.JedisClusterConfig;
import org.apache.storm.redis.common.config.JedisPoolConfig;
import org.apache.storm.redis.common.mapper.RedisDataTypeDescription;
import org.apache.storm.redis.common.mapper.RedisFilterMapper;
import org.apache.storm.topology.OutputFieldsGetter;
import org.apache.storm.tuple.Tuple;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RedisFilterBolt_ESTest extends RedisFilterBolt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig("Oc1<&@^L", 258, 0, "Oc1<&@^L", (-1427));
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.LIST;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("Oc1<&@^L").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("Failure during execution of task").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig();
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.GEO;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("com.google.common.base.Predicates$AndPredicate").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("com.google.common.base.Predicates$AndPredicate").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.execute((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig();
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.HYPER_LOG_LOG;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("com.google.common.base.Predicates$AndPredicate").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("com.google.common.base.Predicates$AndPredicate").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.execute((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HashSet<InetSocketAddress> hashSet0 = new HashSet<InetSocketAddress>();
      JedisClusterConfig jedisClusterConfig0 = new JedisClusterConfig(hashSet0, (-3285), (-460), "");
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.SORTED_SET;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisClusterConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig();
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.HASH;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig("okS$v`|H$yF", 258, 0, "okS$v`|H$yF", (-1427));
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.SET;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn(".s?5lf;nf1jQmqy!").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig();
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.STRING;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("maxDepth must be > 0.").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      doReturn("org.apache.storm.redis.bolt.RedisFilterBolt$1").when(redisFilterMapper0).getKeyFromTuple(any(org.apache.storm.tuple.ITuple.class));
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
      // Undeclared exception!
      try { 
        redisFilterBolt0.process((Tuple) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      JedisPoolConfig jedisPoolConfig0 = new JedisPoolConfig();
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.SET;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      RedisFilterBolt redisFilterBolt0 = null;
      try {
        redisFilterBolt0 = new RedisFilterBolt(jedisPoolConfig0, redisFilterMapper0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // additionalKey should be defined
         //
         verifyException("org.apache.storm.redis.bolt.RedisFilterBolt", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      HashSet<InetSocketAddress> hashSet0 = new HashSet<InetSocketAddress>();
      JedisClusterConfig jedisClusterConfig0 = new JedisClusterConfig(hashSet0, (-3285), (-460), "");
      RedisDataTypeDescription.RedisDataType redisDataTypeDescription_RedisDataType0 = RedisDataTypeDescription.RedisDataType.SORTED_SET;
      RedisDataTypeDescription redisDataTypeDescription0 = mock(RedisDataTypeDescription.class, new ViolatedAssumptionAnswer());
      doReturn("").when(redisDataTypeDescription0).getAdditionalKey();
      doReturn(redisDataTypeDescription_RedisDataType0).when(redisDataTypeDescription0).getDataType();
      RedisFilterMapper redisFilterMapper0 = mock(RedisFilterMapper.class, new ViolatedAssumptionAnswer());
      doReturn(redisDataTypeDescription0).when(redisFilterMapper0).getDataTypeDescription();
      RedisFilterBolt redisFilterBolt0 = new RedisFilterBolt(jedisClusterConfig0, redisFilterMapper0);
      OutputFieldsGetter outputFieldsGetter0 = new OutputFieldsGetter();
      redisFilterBolt0.declareOutputFields(outputFieldsGetter0);
  }
}
