/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Aug 31 21:26:14 GMT 2026
 */

package org.apache.storm.redis.bolt;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class RedisFilterBolt_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.storm.redis.bolt.RedisFilterBolt"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(RedisFilterBolt_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.storm.topology.OutputFieldsDeclarer",
      "org.apache.storm.redis.common.mapper.RedisMapper",
      "org.apache.storm.task.TopologyContext",
      "org.apache.storm.topology.base.BaseComponent",
      "org.apache.storm.shade.net.minidev.json.JSONAware",
      "org.apache.storm.redis.bolt.RedisFilterBolt$1",
      "org.apache.storm.task.GeneralTopologyContext",
      "org.apache.storm.tuple.Tuple",
      "org.apache.storm.task.WorkerTopologyContext",
      "org.apache.storm.task.OutputCollector",
      "org.apache.storm.redis.common.mapper.RedisDataTypeDescription",
      "org.apache.storm.redis.common.config.JedisPoolConfig",
      "org.apache.storm.task.IMetricsContext",
      "org.apache.storm.task.IErrorReporter",
      "org.apache.storm.redis.bolt.RedisFilterBolt",
      "org.apache.storm.topology.base.BaseRichBolt",
      "org.apache.storm.topology.base.BaseTickTupleAwareRichBolt",
      "org.apache.storm.task.IBolt",
      "org.apache.storm.redis.common.mapper.RedisDataTypeDescription$RedisDataType",
      "org.apache.storm.topology.OutputFieldsGetter",
      "org.apache.storm.tuple.Fields",
      "org.apache.storm.tuple.ITuple",
      "org.apache.storm.redis.common.config.JedisClusterConfig",
      "org.apache.storm.task.IOutputCollector",
      "org.apache.storm.redis.common.container.JedisCommandsContainer",
      "org.apache.storm.redis.bolt.AbstractRedisBolt",
      "org.apache.storm.redis.common.mapper.TupleMapper",
      "org.apache.storm.topology.IRichBolt",
      "org.apache.storm.redis.common.mapper.RedisFilterMapper",
      "org.apache.storm.topology.IComponent"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.apache.storm.redis.common.mapper.RedisDataTypeDescription", false, RedisFilterBolt_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.storm.redis.common.mapper.RedisFilterMapper", false, RedisFilterBolt_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(RedisFilterBolt_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.storm.topology.base.BaseComponent",
      "org.apache.storm.topology.base.BaseRichBolt",
      "org.apache.storm.topology.base.BaseTickTupleAwareRichBolt",
      "org.apache.storm.redis.bolt.AbstractRedisBolt",
      "org.apache.storm.redis.bolt.RedisFilterBolt",
      "org.apache.storm.redis.common.mapper.RedisDataTypeDescription$RedisDataType",
      "org.apache.storm.redis.bolt.RedisFilterBolt$1",
      "org.apache.storm.redis.common.config.JedisClusterConfig",
      "com.google.common.base.Preconditions",
      "redis.clients.jedis.HostAndPort",
      "org.apache.storm.shade.io.netty.util.DefaultAttributeMap",
      "org.apache.storm.shade.io.netty.util.internal.logging.InternalLoggerFactory",
      "org.apache.storm.shade.io.netty.util.internal.logging.Slf4JLoggerFactory",
      "org.apache.storm.shade.io.netty.util.internal.logging.Slf4JLoggerFactory$NopInstanceHolder",
      "org.apache.storm.shade.io.netty.util.internal.logging.AbstractInternalLogger",
      "org.apache.storm.shade.io.netty.util.internal.logging.LocationAwareSlf4JLogger",
      "org.apache.storm.shade.io.netty.util.internal.ObjectUtil",
      "org.apache.storm.shade.io.netty.channel.AbstractChannel",
      "org.apache.storm.shade.io.netty.channel.ChannelMetadata",
      "org.apache.storm.shade.io.netty.channel.kqueue.AbstractKQueueChannel",
      "org.apache.storm.shade.io.netty.channel.kqueue.AbstractKQueueDatagramChannel",
      "org.apache.storm.shade.io.netty.util.internal.SystemPropertyUtil",
      "org.apache.storm.shade.io.netty.util.internal.StringUtil",
      "org.apache.storm.shade.io.netty.channel.kqueue.KQueueDatagramChannel",
      "org.apache.storm.shade.io.netty.channel.unix.FileDescriptor",
      "org.apache.storm.shade.io.netty.channel.unix.Socket",
      "org.apache.storm.shade.io.netty.channel.kqueue.BsdSocket",
      "org.apache.storm.redis.common.config.JedisPoolConfig",
      "org.apache.storm.shade.io.netty.channel.epoll.AbstractEpollChannel",
      "org.apache.storm.shade.io.netty.channel.epoll.AbstractEpollServerChannel",
      "org.apache.storm.shade.io.netty.channel.epoll.EpollServerSocketChannel",
      "org.apache.storm.shade.io.netty.channel.epoll.LinuxSocket",
      "org.apache.storm.thrift.TConfiguration$Builder",
      "org.apache.storm.thrift.TConfiguration",
      "org.apache.storm.thrift.transport.TTransport",
      "org.apache.storm.thrift.transport.TEndpointTransport",
      "org.apache.storm.thrift.transport.TMemoryBuffer",
      "org.apache.storm.thrift.TByteArrayOutputStream",
      "org.apache.storm.thrift.TException",
      "org.apache.storm.thrift.transport.TTransportException",
      "org.apache.storm.thrift.transport.TIOStreamTransport",
      "org.apache.storm.thrift.transport.TSocket",
      "org.apache.storm.redis.common.mapper.RedisDataTypeDescription",
      "org.apache.storm.topology.OutputFieldsGetter",
      "org.apache.storm.thrift.transport.TMemoryInputTransport",
      "org.apache.storm.thrift.transport.TZlibTransport",
      "org.apache.storm.thrift.transport.TTransportInputStream",
      "org.apache.storm.thrift.transport.TTransportOutputStream",
      "org.apache.storm.thrift.transport.TStandardFile",
      "org.apache.storm.thrift.protocol.TStruct",
      "org.apache.storm.thrift.protocol.TField",
      "org.apache.storm.generated.SupervisorInfo$SupervisorInfoStandardSchemeFactory",
      "org.apache.storm.generated.SupervisorInfo$SupervisorInfoTupleSchemeFactory",
      "org.apache.storm.generated.SupervisorInfo$_Fields",
      "org.apache.storm.thrift.meta_data.FieldMetaData",
      "org.apache.storm.thrift.meta_data.FieldValueMetaData",
      "org.apache.storm.thrift.meta_data.ListMetaData",
      "org.apache.storm.thrift.meta_data.MapMetaData",
      "org.apache.storm.generated.SupervisorInfo",
      "org.apache.storm.thrift.EncodingUtils",
      "org.apache.storm.executor.Executor",
      "org.apache.storm.generated.StreamInfo$StreamInfoStandardSchemeFactory",
      "org.apache.storm.generated.StreamInfo$StreamInfoTupleSchemeFactory",
      "org.apache.storm.generated.StreamInfo$_Fields",
      "org.apache.storm.generated.StreamInfo",
      "org.apache.storm.tuple.Fields",
      "org.apache.storm.tuple.TupleImpl",
      "org.apache.storm.generated.StormTopology$StormTopologyStandardSchemeFactory",
      "org.apache.storm.generated.StormTopology$StormTopologyTupleSchemeFactory",
      "org.apache.storm.generated.StormTopology$_Fields",
      "org.apache.storm.thrift.meta_data.StructMetaData",
      "org.apache.storm.thrift.meta_data.SetMetaData",
      "org.apache.storm.generated.StormTopology",
      "org.apache.storm.task.GeneralTopologyContext",
      "org.apache.storm.validation.ConfigValidation",
      "org.apache.storm.shade.com.google.common.collect.Lists",
      "org.apache.storm.shade.com.google.common.base.Preconditions",
      "org.apache.storm.shade.com.google.common.collect.CollectPreconditions",
      "org.apache.storm.shade.com.google.common.primitives.IntsMethodsForWeb",
      "org.apache.storm.shade.com.google.common.primitives.Ints",
      "org.apache.storm.shade.org.yaml.snakeyaml.Yaml",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.BaseConstructor",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.AbstractConstruct",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor",
      "org.apache.storm.shade.org.yaml.snakeyaml.LoaderOptions",
      "org.apache.storm.shade.org.yaml.snakeyaml.inspector.UnTrustedTagInspector",
      "org.apache.storm.shade.org.yaml.snakeyaml.nodes.NodeId",
      "org.apache.storm.shade.org.yaml.snakeyaml.internal.Logger",
      "org.apache.storm.shade.org.yaml.snakeyaml.TypeDescription",
      "org.apache.storm.shade.org.yaml.snakeyaml.external.com.google.gdata.util.common.base.UnicodeEscaper$2",
      "org.apache.storm.shade.org.yaml.snakeyaml.external.com.google.gdata.util.common.base.UnicodeEscaper",
      "org.apache.storm.shade.org.yaml.snakeyaml.external.com.google.gdata.util.common.base.PercentEscaper",
      "org.apache.storm.shade.org.yaml.snakeyaml.util.UriEncoder",
      "org.apache.storm.shade.org.yaml.snakeyaml.nodes.Tag",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlNull",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlBool",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlInt",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlFloat",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlBinary",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlTimestamp",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlOmap",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlPairs",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSet",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlStr",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq",
      "org.apache.storm.shade.org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.BaseRepresenter",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.Representer",
      "org.apache.storm.shade.org.yaml.snakeyaml.DumperOptions",
      "org.apache.storm.shade.org.yaml.snakeyaml.DumperOptions$ScalarStyle",
      "org.apache.storm.shade.org.yaml.snakeyaml.DumperOptions$FlowStyle",
      "org.apache.storm.shade.org.yaml.snakeyaml.DumperOptions$LineBreak",
      "org.apache.storm.shade.org.yaml.snakeyaml.DumperOptions$NonPrintableStyle",
      "org.apache.storm.shade.org.yaml.snakeyaml.serializer.NumberAnchorGenerator",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.BaseRepresenter$1",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentNull",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentString",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentBoolean",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentUuid",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentByteArray",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentPrimitiveArray",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentNumber",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentList",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentSet",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentIterator",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentArray",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentDate",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.SafeRepresenter$RepresentEnum",
      "org.apache.storm.shade.org.yaml.snakeyaml.representer.Representer$RepresentJavaBean",
      "org.apache.storm.shade.org.yaml.snakeyaml.introspector.PropertyUtils",
      "org.apache.storm.shade.org.yaml.snakeyaml.util.PlatformFeatureDetector",
      "org.apache.storm.shade.org.yaml.snakeyaml.introspector.BeanAccess",
      "org.apache.storm.shade.org.yaml.snakeyaml.resolver.Resolver",
      "org.apache.storm.shade.org.yaml.snakeyaml.resolver.ResolverTuple",
      "org.apache.storm.shade.org.yaml.snakeyaml.reader.StreamReader",
      "org.apache.storm.shade.org.yaml.snakeyaml.composer.Composer",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl",
      "org.apache.storm.shade.org.yaml.snakeyaml.scanner.ScannerImpl",
      "org.apache.storm.shade.org.yaml.snakeyaml.util.ArrayStack",
      "org.apache.storm.shade.org.yaml.snakeyaml.error.Mark",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.Token",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.StreamStartToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.VersionTagsTuple",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseStreamStart",
      "org.apache.storm.shade.org.yaml.snakeyaml.comments.CommentEventsCollector",
      "org.apache.storm.shade.org.yaml.snakeyaml.comments.CommentType",
      "org.apache.storm.shade.org.yaml.snakeyaml.comments.CommentEventsCollector$1",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.Event",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.StreamStartEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.Event$ID",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.Token$ID",
      "org.apache.storm.shade.org.yaml.snakeyaml.scanner.Constant",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.CommentToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.scanner.SimpleKey",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.ScalarToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.KeyToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.BlockMappingStartToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.ValueToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.DocumentStartEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockNode",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.NodeEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.CollectionStartEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.MappingStartEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingFirstKey",
      "org.apache.storm.shade.org.yaml.snakeyaml.resolver.Resolver$1",
      "org.apache.storm.shade.org.yaml.snakeyaml.nodes.Node",
      "org.apache.storm.shade.org.yaml.snakeyaml.nodes.CollectionNode",
      "org.apache.storm.shade.org.yaml.snakeyaml.nodes.MappingNode",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.ImplicitTuple",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.ScalarEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.nodes.ScalarNode",
      "org.apache.storm.shade.org.yaml.snakeyaml.nodes.NodeTuple",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.BlockSequenceStartToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.BlockEntryToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.SequenceStartEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceFirstEntry",
      "org.apache.storm.shade.org.yaml.snakeyaml.nodes.SequenceNode",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntryKey",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntryValue",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.BlockEndToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.CollectionEndEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.SequenceEndEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.FlowSequenceStartToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceFirstEntry",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseFlowSequenceEntry",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.FlowSequenceEndToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.MappingEndEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.tokens.StreamEndToken",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.DocumentEndEvent",
      "org.apache.storm.shade.org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart",
      "org.apache.storm.shade.org.yaml.snakeyaml.events.StreamEndEvent",
      "org.apache.storm.serialization.GzipThriftSerializationDelegate",
      "org.apache.storm.utils.Utils",
      "org.apache.storm.Config",
      "org.apache.storm.utils.ConfigUtils",
      "org.apache.storm.thrift.transport.TSimpleFileTransport",
      "org.apache.storm.thrift.protocol.TProtocol",
      "org.apache.storm.thrift.protocol.TCompactProtocol",
      "org.apache.storm.thrift.protocol.TTupleProtocol",
      "org.apache.storm.thrift.protocol.ShortStack",
      "org.apache.storm.thrift.protocol.TSet",
      "org.apache.storm.shade.io.netty.channel.kqueue.AbstractKQueueStreamChannel",
      "org.apache.storm.shade.io.netty.channel.kqueue.KQueueSocketChannel",
      "org.apache.storm.pacemaker.PacemakerClientPool",
      "org.apache.storm.cluster.ClusterStateContext",
      "org.apache.storm.cluster.ZKStateStorage",
      "org.apache.storm.callback.DefaultWatcherCallBack",
      "org.apache.storm.zookeeper.ClientZookeeper",
      "org.apache.storm.utils.ZookeeperAuthInfo",
      "org.apache.storm.utils.CuratorUtils",
      "org.apache.storm.thrift.transport.TByteBuffer",
      "org.apache.storm.generated.Assignment$AssignmentStandardSchemeFactory",
      "org.apache.storm.generated.Assignment$AssignmentTupleSchemeFactory",
      "org.apache.storm.generated.Assignment$_Fields",
      "org.apache.storm.generated.Assignment",
      "org.apache.storm.utils.TupleUtils",
      "org.apache.storm.daemon.Task",
      "org.apache.storm.thrift.transport.AutoExpandingBufferReadTransport",
      "org.apache.storm.thrift.transport.AutoExpandingBuffer",
      "org.apache.storm.task.OutputCollector",
      "org.apache.storm.thrift.transport.AutoExpandingBufferWriteTransport",
      "org.apache.storm.shade.io.netty.channel.epoll.AbstractEpollStreamChannel",
      "org.apache.storm.shade.io.netty.channel.epoll.EpollSocketChannel",
      "org.apache.storm.thrift.transport.TNonblockingTransport",
      "org.apache.storm.thrift.transport.TNonblockingSocket",
      "org.apache.storm.thrift.transport.TFileTransport",
      "org.apache.storm.thrift.transport.TFileTransport$TailPolicy",
      "org.apache.storm.tuple.MessageId",
      "org.apache.storm.shade.org.apache.zookeeper.server.ServerCnxn",
      "org.apache.storm.shade.org.apache.zookeeper.server.DumbWatcher",
      "org.apache.storm.shade.org.apache.zookeeper.compat.ProtocolManager",
      "org.apache.storm.shade.org.apache.zookeeper.server.ServerCnxn$DisconnectReason",
      "org.apache.storm.shade.org.apache.zookeeper.proto.ReplyHeader",
      "org.apache.storm.thrift.protocol.TList",
      "org.apache.storm.thrift.transport.TMemoryTransport",
      "org.apache.storm.shade.org.apache.zookeeper.Login",
      "org.apache.storm.shade.org.apache.zookeeper.server.ServerCnxnFactory",
      "org.apache.storm.shade.org.apache.zookeeper.server.NIOServerCnxnFactory$1",
      "org.apache.storm.shade.org.apache.zookeeper.server.NIOServerCnxnFactory",
      "org.apache.storm.shade.io.netty.channel.kqueue.AbstractKQueueServerChannel",
      "org.apache.storm.shade.io.netty.channel.kqueue.KQueueServerSocketChannel",
      "org.apache.storm.thrift.transport.TSaslTransport",
      "org.apache.storm.thrift.transport.TSaslServerTransport",
      "org.apache.storm.redis.common.container.JedisCommandsContainerBuilder",
      "redis.clients.jedis.UnifiedJedis",
      "redis.clients.jedis.JedisCluster",
      "org.apache.storm.messaging.local.Context",
      "redis.clients.jedis.Builder",
      "redis.clients.jedis.Response",
      "com.esotericsoftware.kryo.io.Output",
      "org.apache.storm.thrift.protocol.TProtocolException",
      "com.esotericsoftware.kryo.io.Input",
      "org.apache.storm.thrift.protocol.TMap"
    );
  }
}
