/*
 * This file was automatically generated by EvoSuite
 * Mon Aug 31 19:27:51 GMT 2026
 */

package org.apache.storm.daemon.ui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import clojure.lang.MapEntry;
import clojure.lang.PersistentVector;
import jakarta.ws.rs.core.Response;
import java.sql.DataTruncation;
import java.sql.SQLInvalidAuthorizationSpecException;
import java.sql.SQLNonTransientConnectionException;
import java.util.AbstractMap;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ServiceConfigurationError;
import java.util.concurrent.ConcurrentSkipListMap;
import java.util.concurrent.LinkedBlockingDeque;
import javax.swing.JLayeredPane;
import org.apache.storm.daemon.ui.IConfigurator;
import org.apache.storm.daemon.ui.UIHelpers;
import org.apache.storm.generated.ClusterSummary;
import org.apache.storm.generated.ComponentPageInfo;
import org.apache.storm.generated.ExecutorInfo;
import org.apache.storm.generated.ExecutorSummary;
import org.apache.storm.generated.GlobalStreamId;
import org.apache.storm.generated.Grouping;
import org.apache.storm.generated.Nimbus;
import org.apache.storm.generated.ProfileRequest;
import org.apache.storm.generated.SupervisorPageInfo;
import org.apache.storm.generated.SupervisorSummary;
import org.apache.storm.generated.TopologyHistoryInfo;
import org.apache.storm.generated.TopologySummary;
import org.apache.storm.thrift.TConfiguration;
import org.apache.storm.thrift.protocol.TBinaryProtocol;
import org.apache.storm.thrift.protocol.TCompactProtocol;
import org.apache.storm.thrift.protocol.TJSONProtocol;
import org.apache.storm.thrift.protocol.TSimpleJSONProtocol;
import org.apache.storm.thrift.protocol.TTupleProtocol;
import org.apache.storm.thrift.transport.TMemoryInputTransport;
import org.apache.storm.thrift.transport.TSimpleFileTransport;
import org.apache.storm.thrift.transport.TSocket;
import org.apache.storm.thrift.transport.TTransport;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.FilterHolder;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.glassfish.jersey.client.ClientAsyncExecutorLiteral;
import org.glassfish.jersey.server.BackgroundSchedulerLiteral;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UIHelpers_ESTest extends UIHelpers_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.unauthorizedUserJson((String) null);
      String string0 = UIHelpers.getWorkerDumpLink("Q$8HcU*YJ~N1", 515L, "http://Q%248HcU*YJ%7EN1:null/api/v1/daemonlog?file=nimbus.log", map0);
      assertEquals("http://Q%25248HcU*YJ%257EN1:null/api/v1/dumps/http%253A%252F%252FQ%2525248HcU*YJ%25257EN1%253Anull%252Fapi%252Fv1%252Fdaemonlog%253Ffile%253Dnimbus.log/Q%25248HcU*YJ%257EN1%3A515", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = UIHelpers.sanitizeStreamName("clojure.pprint$inc_s");
      assertEquals("clojure.pprint_inc_s", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SupervisorPageInfo supervisorPageInfo0 = new SupervisorPageInfo();
      List<Map> list0 = (List<Map>)UIHelpers.getWorkerSummaries(supervisorPageInfo0, (Map<String, Object>) null);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ConcurrentSkipListMap<String, Object> concurrentSkipListMap0 = new ConcurrentSkipListMap<String, Object>();
      // Undeclared exception!
      try { 
        UIHelpers.getLogviewerPort(concurrentSkipListMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.unauthorizedUserJson((String) null);
      String string0 = UIHelpers.getSupervisorLogLink("Q$8HcU*YJ~N1", map0);
      assertEquals("http://Q%248HcU*YJ%7EN1:null/api/v1/daemonlog?file=supervisor.log", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ClusterSummary clusterSummary0 = new ClusterSummary();
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      // Undeclared exception!
      try { 
        UIHelpers.getClusterSummary(clusterSummary0, "version", hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      LinkedBlockingDeque<ClientAsyncExecutorLiteral> linkedBlockingDeque0 = new LinkedBlockingDeque<ClientAsyncExecutorLiteral>(3684);
      PersistentVector persistentVector0 = PersistentVector.create((Iterable) linkedBlockingDeque0);
      MapEntry mapEntry0 = MapEntry.create(hashMap0, "STARTING");
      ClusterSummary clusterSummary0 = new ClusterSummary(persistentVector0, persistentVector0, mapEntry0);
      Map<String, Object> map0 = UIHelpers.getClusterSummary(clusterSummary0, "STOPPED", hashMap0);
      assertEquals(23, map0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SQLInvalidAuthorizationSpecException sQLInvalidAuthorizationSpecException0 = new SQLInvalidAuthorizationSpecException();
      DataTruncation dataTruncation0 = new DataTruncation((-1), true, false, 1431, 1431, sQLInvalidAuthorizationSpecException0);
      Map map0 = UIHelpers.exceptionToJson(dataTruncation0, 300);
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SQLInvalidAuthorizationSpecException sQLInvalidAuthorizationSpecException0 = new SQLInvalidAuthorizationSpecException();
      DataTruncation dataTruncation0 = new DataTruncation(502, true, false, 1431, 0, sQLInvalidAuthorizationSpecException0);
      SQLNonTransientConnectionException sQLNonTransientConnectionException0 = new SQLNonTransientConnectionException("", "", 273066, dataTruncation0);
      Map map0 = UIHelpers.exceptionToJson(sQLNonTransientConnectionException0, 273066);
      assertEquals(2, map0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SQLInvalidAuthorizationSpecException sQLInvalidAuthorizationSpecException0 = new SQLInvalidAuthorizationSpecException();
      Map map0 = UIHelpers.exceptionToJson(sQLInvalidAuthorizationSpecException0, 7);
      assertEquals(2, map0.size());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        UIHelpers.getJsonResponseBody(object0, "Hz]]Sa.!0!&b'Zm*", false);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.Object cannot be cast to class java.lang.String (java.lang.Object and java.lang.String are in module java.base of loader 'bootstrap')
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ConcurrentSkipListMap<String, Object> concurrentSkipListMap0 = new ConcurrentSkipListMap<String, Object>();
      Map map0 = UIHelpers.getJsonResponseHeaders(":all-time", concurrentSkipListMap0);
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Integer integer0 = JLayeredPane.POPUP_LAYER;
      Boolean boolean0 = Boolean.TRUE;
      Server server0 = UIHelpers.jettyCreateServer(integer0, "Jetty(11.0.24)", integer0, integer0, boolean0);
      assertTrue(server0.isStopped());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Integer integer0 = JLayeredPane.POPUP_LAYER;
      try { 
        UIHelpers.stormRunJetty(integer0, "alternativeWorkerVersions", integer0, integer0, (IConfigurator) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("org.evosuite.runtime.mock.java.lang.MockException", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer integer0 = JLayeredPane.MODAL_LAYER;
      Integer integer1 = JLayeredPane.DEFAULT_LAYER;
      Server server0 = UIHelpers.jettyCreateServer(integer0, "clojure.pprint$pretty_writer$fn__10223", integer1, (Boolean) null);
      assertFalse(server0.isFailed());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String string0 = UIHelpers.prettyUptimeSec(16384000);
      assertEquals("189d 15h 6m 40s", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ExecutorSummary executorSummary0 = new ExecutorSummary();
      Map<String, Object> map0 = UIHelpers.getStatMapFromExecutorSummary(executorSummary0);
      // Undeclared exception!
      try { 
        UIHelpers.getAllTopologiesSummary((List<TopologySummary>) null, map0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      String string0 = UIHelpers.getWorkerLogLink("http://:null/api/v1/log?file=", 4, hashMap0, (String) null);
      assertEquals("http://http%3A%2F%2F%3Anull%2Fapi%2Fv1%2Flog%3Ffile%3D:null/api/v1/log?file=null%5C4%5Cworker.log", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.unauthorizedUserJson("$*iW*|]dG:v4v");
      SupervisorSummary supervisorSummary0 = new SupervisorSummary("activate", 2259, 1195725856, 2259, "?% ");
      // Undeclared exception!
      try { 
        UIHelpers.getPrettifiedSupervisorMap(supervisorSummary0, map0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Server server0 = new Server(3684);
      Integer integer0 = JLayeredPane.PALETTE_LAYER;
      Boolean boolean0 = Boolean.TRUE;
      UIHelpers.configSsl(server0, integer0, "", "yEv,N?)?Ks", "FAILED", "com\"fasterxml.jrcPson.databind.deser.std.ObjectArrLyDeserialzer", "5+", "com\"fasterxml.jrcPson.databind.deser.std.ObjectArrLyDeserialzer", "|{Fym", boolean0, boolean0, false);
      assertFalse(server0.isFailed());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        UIHelpers.makeStandardResponse(object0, "^w{VWy#L: ]wk|X`");
        fail("Expecting exception: ServiceConfigurationError");
      
      } catch(ServiceConfigurationError e) {
         //
         // jakarta.ws.rs.ext.RuntimeDelegate: org.glassfish.jersey.internal.RuntimeDelegateImpl not a subtype
         //
         verifyException("java.util.ServiceLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ExecutorInfo executorInfo0 = new ExecutorInfo(16384000, 1942);
      String string0 = UIHelpers.prettyExecutorInfo(executorInfo0);
      assertEquals("[16384000-1942]", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      FilterHolder filterHolder0 = UIHelpers.mkAccessLoggingFilterHandle();
      assertFalse(filterHolder0.isStarting());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TSimpleFileTransport tSimpleFileTransport0 = new TSimpleFileTransport("$MF*U%CjP]GV!", true, true, true);
      TSimpleJSONProtocol tSimpleJSONProtocol0 = new TSimpleJSONProtocol(tSimpleFileTransport0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tSimpleJSONProtocol0, tSimpleJSONProtocol0);
      Map<String, Object> map0 = UIHelpers.getProfilingDisabled();
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingDump(nimbus_Client0, "$MF*U%CjP]GV!", "", map0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TopologyHistoryInfo topologyHistoryInfo0 = new TopologyHistoryInfo();
      Map<String, Object> map0 = UIHelpers.getTopologyHistoryInfo(topologyHistoryInfo0);
      TBinaryProtocol tBinaryProtocol0 = new TBinaryProtocol((TTransport) null);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tBinaryProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingStart(nimbus_Client0, (String) null, (String) null, "fMKk9-HuD", map0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"fMKk9-HuD\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.prettyUptimeMs("");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyDeactivate((Nimbus.Iface) null, ";");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TConfiguration tConfiguration0 = new TConfiguration();
      TSimpleFileTransport tSimpleFileTransport0 = new TSimpleFileTransport(tConfiguration0, "2$YTw.UqPv", true, true, true);
      TBinaryProtocol tBinaryProtocol0 = new TBinaryProtocol(tSimpleFileTransport0, 104857600, 64);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tBinaryProtocol0);
      try { 
        UIHelpers.putTopologyDebugActionSpct(nimbus_Client0, "STOPPING", "b[]Y3k}t2=/-&jE`#4", (String) null, "STARTING");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot read. Remote side has closed. Tried to read 4 bytes, but only got 0 bytes. (This is often indicative of an internal error on the server side. Please check your server logs.)
         //
         verifyException("org.apache.storm.thrift.transport.TTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ExecutorSummary executorSummary0 = new ExecutorSummary();
      Map<String, Object> map0 = UIHelpers.getStatMapFromExecutorSummary(executorSummary0);
      ComponentPageInfo componentPageInfo0 = new ComponentPageInfo();
      // Undeclared exception!
      try { 
        UIHelpers.unpackSpoutPageInfo(componentPageInfo0, "bolts", "peZ'q^vhklX}@N1H", false, map0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Integer integer0 = JLayeredPane.DEFAULT_LAYER;
      IConfigurator iConfigurator0 = mock(IConfigurator.class, new ViolatedAssumptionAnswer());
      try { 
        UIHelpers.stormRunJetty(integer0, integer0, iConfigurator0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("org.evosuite.runtime.mock.java.lang.MockException", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.getTopologyOpResponse("", "");
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      byte[] byteArray0 = new byte[5];
      TMemoryInputTransport tMemoryInputTransport0 = new TMemoryInputTransport(byteArray0);
      TCompactProtocol tCompactProtocol0 = new TCompactProtocol(tMemoryInputTransport0, 32767L, (byte)0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tCompactProtocol0, tCompactProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingRestartWorker(nimbus_Client0, "", (String) null, hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      UIHelpers uIHelpers0 = new UIHelpers();
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TConfiguration tConfiguration0 = new TConfiguration();
      byte[] byteArray0 = new byte[1];
      TMemoryInputTransport tMemoryInputTransport0 = new TMemoryInputTransport(tConfiguration0, byteArray0, 104857600, 5);
      TJSONProtocol tJSONProtocol0 = new TJSONProtocol(tMemoryInputTransport0, false);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tJSONProtocol0, tJSONProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.putTopologyActivate(nimbus_Client0, "logviewer.https.port");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // No writing allowed!
         //
         verifyException("org.apache.storm.thrift.transport.TMemoryInputTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ServletContextHandler servletContextHandler0 = new ServletContextHandler((-1846264243));
      PersistentVector persistentVector0 = PersistentVector.adopt(servletContextHandler0.SERVLET_LISTENER_TYPES);
      // Undeclared exception!
      try { 
        UIHelpers.configFilters(servletContextHandler0, persistentVector0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class java.lang.Class cannot be cast to class org.apache.storm.daemon.ui.FilterConfiguration (java.lang.Class is in module java.base of loader 'bootstrap'; org.apache.storm.daemon.ui.FilterConfiguration is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @4d98fdd3)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      String string0 = UIHelpers.prettyUptimeMs(72);
      assertEquals("72ms", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      // Undeclared exception!
      try { 
        UIHelpers.getWindowHint("^w{VWy#L: ]wk|X`");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"^w{VWy#L: ]wk|X`\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      GlobalStreamId globalStreamId0 = new GlobalStreamId("(?![A-Za-z_-.]).", ":all-time");
      Grouping grouping0 = new Grouping();
      AbstractMap.SimpleImmutableEntry<GlobalStreamId, Grouping> abstractMap_SimpleImmutableEntry0 = new AbstractMap.SimpleImmutableEntry<GlobalStreamId, Grouping>(globalStreamId0, grouping0);
      // Undeclared exception!
      try { 
        UIHelpers.getInputMap(abstractMap_SimpleImmutableEntry0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      TSocket tSocket0 = new TSocket("Offline", (-5450), 344);
      TBinaryProtocol tBinaryProtocol0 = new TBinaryProtocol(tSocket0, false, false);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tBinaryProtocol0);
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyProfilingDumpJstack(nimbus_Client0, "", "org.apache.logging.log4j.core.appender.rolling.action.IfAccumulatedFileCount", hashMap0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 1 out of bounds for length 1
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      TopologySummary topologySummary0 = new TopologySummary();
      // Undeclared exception!
      try { 
        UIHelpers.getTopologyMap(topologySummary0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.net.URLEncoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      TConfiguration tConfiguration0 = new TConfiguration();
      TSocket tSocket0 = new TSocket(tConfiguration0, "No health check named ", 16384000, 64);
      TTupleProtocol tTupleProtocol0 = new TTupleProtocol(tSocket0);
      Nimbus.Client nimbus_Client0 = new Nimbus.Client(tTupleProtocol0);
      try { 
        UIHelpers.putTopologyRebalance(nimbus_Client0, "_G(c", (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Cannot write to null outputStream
         //
         verifyException("org.apache.storm.thrift.transport.TIOStreamTransport", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ConcurrentSkipListMap<String, BackgroundSchedulerLiteral> concurrentSkipListMap0 = new ConcurrentSkipListMap<String, BackgroundSchedulerLiteral>();
      // Undeclared exception!
      try { 
        UIHelpers.getActiveAction((ProfileRequest) null, concurrentSkipListMap0, "org.apache.storm.generated.TopologyInfo$TopologyInfoStandardScheme");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.storm.daemon.ui.UIHelpers", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Response.Status response_Status0 = Response.Status.OK;
      // Undeclared exception!
      try { 
        UIHelpers.makeStandardResponse((Object) null, "$", response_Status0);
       //  fail("Expecting exception: ServiceConfigurationError");
       // Unstable assertion
      } catch(ServiceConfigurationError e) {
         //
         // jakarta.ws.rs.ext.RuntimeDelegate: org.glassfish.jersey.internal.RuntimeDelegateImpl not a subtype
         //
         verifyException("java.util.ServiceLoader", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Integer integer0 = JLayeredPane.MODAL_LAYER;
      Server server0 = UIHelpers.jettyCreateServer(integer0, "clojure.pprint$pretty_writer$fn__10223", integer0, (Boolean) null);
      assertTrue(server0.isStopped());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Map<String, Object> map0 = UIHelpers.unauthorizedUserJson((String) null);
      UIHelpers.getNimbusLogLink("Q$8HcU*YJ~N1", map0);
  }
}
